export const personalInfo = {
  name: 'Vansh Shah',
  title: 'MCA Student & Developer',
  tagline: 'Final-year CS student building real-world projects and solving hard problems — one commit at a time.',
  bio: `I'm a final-year Computer Science student passionate about building things that live on the internet. I love turning ideas into polished, functional products — from sleek frontends to robust APIs.

I'm actively looking for internship and entry-level opportunities where I can contribute, learn from great engineers, and keep growing.`,
  email: 'vanshshah1011@gmail.com',
  location: 'San Francisco, CA',
  availability: 'Actively seeking opportunities',
  social: {
    github: 'https://github.com',
    linkedin: 'https://linkedin.com',
    leetcode: 'https://leetcode.com',
  }
}

export const skills = [
  { category: 'Frontend', items: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Framer Motion', 'Three.js'] },
  { category: 'Backend', items: ['Node.js', 'Express', 'Python', 'REST APIs', 'PostgreSQL', 'MongoDB'] },
  { category: 'Tools & Platforms', items: ['Git', 'GitHub', 'Vercel', 'Firebase', 'Figma', 'VS Code'] },
  { category: 'CS Fundamentals', items: ['Data Structures', 'Algorithms', 'OOP', 'System Design', 'DBMS', 'OS'] },
]

export const proficiencies = [
  { label: 'Frontend Development', level: 88 },
  { label: 'Backend / APIs', level: 75 },
  { label: 'Data Structures & Algorithms', level: 82 },
  { label: 'UI/UX Design', level: 70 },
  { label: 'Database Design', level: 68 },
]

export const dsaStats = {
  platform: 'LeetCode',
  url: 'https://leetcode.com',
  username: 'alexchen',
  totalSolved: 320,
  easy: 110,
  medium: 175,
  hard: 35,
  streak: 100,
  ranking: 'Top 8%',
  focusAreas: ['Dynamic Programming', 'Graphs', 'Trees & BSTs', 'Sliding Window', 'Binary Search'],
  recentMilestone: '100-day streak completed 🔥',
  contests: 12,
  contestRating: 1742,
}

export const projects = [
  {
    id: 1,
    slug: 'nebula-ai',
    title: 'Nebula AI Chat',
    description: 'A real-time AI chat app with streaming responses and conversation history — built to learn full-stack development end-to-end.',
    longDescription: `Nebula AI Chat was my first major full-stack project. I wanted to build something that integrated with a real AI API while also learning websockets, state management, and database design.\n\nThe app supports multiple conversations, real-time streaming of AI responses, and a clean chat UI inspired by modern messaging apps.`,
    problem: `I wanted to build a project that would teach me full-stack skills from scratch — authentication, database relationships, real-time communication, and third-party API integration — all in one go.`,
    solution: `I architected a Node.js + Express backend with PostgreSQL for storing conversations, used Server-Sent Events for streaming OpenAI responses token-by-token, and built a React frontend with optimistic UI updates for a snappy UX.`,
    image: null,
    gradient: 'from-blue-600/20 to-violet-600/20',
    accent: '#4f8ef7',
    tags: ['React', 'Node.js', 'OpenAI API', 'PostgreSQL', 'SSE', 'JWT Auth'],
    github: 'https://github.com',
    live: 'https://example.com',
    featured: true,
    learnings: 'Learned SSE vs WebSockets tradeoffs, database normalization, and how to build a streaming UX.',
  },
  {
    id: 2,
    slug: 'phantom-ui',
    title: 'Phantom UI Library',
    description: 'An open-source React component library with 30+ accessible components, full TypeScript support, and a Storybook playground.',
    longDescription: `Phantom UI started as a personal utility kit — I was tired of re-writing the same Button, Modal, and Input components for every project. I decided to formalize it into a proper library with docs.\n\nIt's fully typed with TypeScript, all components follow WCAG 2.1 accessibility standards, and it ships with a Storybook for interactive documentation.`,
    problem: `Re-writing UI primitives for every new project is tedious and leads to inconsistencies. I wanted a personal component library I could drop into any React project instantly.`,
    solution: `Built components with Radix UI primitives for accessibility out of the box, styled with CSS variables for easy theming, and set up automated visual regression testing with Chromatic.`,
    image: null,
    gradient: 'from-cyan-600/20 to-blue-600/20',
    accent: '#00d4ff',
    tags: ['TypeScript', 'React', 'Radix UI', 'Storybook', 'Vitest', 'CSS Variables'],
    github: 'https://github.com',
    live: 'https://example.com',
    featured: true,
    learnings: 'Deepened understanding of component API design, TypeScript generics, and accessibility best practices.',
  },
  {
    id: 3,
    slug: 'pulse-dashboard',
    title: 'Pulse Analytics Dashboard',
    description: 'A data visualization dashboard for tracking personal productivity metrics — built with custom D3.js charts.',
    longDescription: `Pulse is a personal analytics dashboard I built to visualize my own study and coding habits. It pulls data from various sources, processes it, and renders interactive charts.\n\nI built custom D3.js chart components from scratch because I wanted to learn the library deeply rather than relying on wrappers.`,
    problem: `I was tracking my study hours and LeetCode progress in spreadsheets, which was clunky. I wanted a visual dashboard that updated automatically.`,
    solution: `Built a Python scraper to collect data nightly, stored in PostgreSQL, and served via a Next.js API. The frontend uses hand-crafted D3.js visualizations wrapped in React refs.`,
    image: null,
    gradient: 'from-violet-600/20 to-pink-600/20',
    accent: '#8b5cf6',
    tags: ['Next.js', 'D3.js', 'Python', 'PostgreSQL', 'Cron Jobs'],
    github: 'https://github.com',
    live: 'https://example.com',
    featured: false,
    learnings: 'Learned D3.js data binding, Python automation with BeautifulSoup, and database query optimization.',
  },
  {
    id: 4,
    slug: 'archi-3d',
    title: 'Archi 3D Viewer',
    description: 'A browser-based 3D model viewer built with Three.js — lets users upload and inspect GLTF models in real time.',
    longDescription: `Archi was my deep-dive into Three.js and WebGL. The goal was to understand how 3D rendering works in the browser and build something visually impressive.\n\nUsers can drag-and-drop GLTF/GLB files, inspect them with orbit controls, toggle wireframe mode, and adjust lighting in real time.`,
    problem: `Most 3D viewers require desktop software. I wanted to build a lightweight, zero-install viewer that works entirely in the browser.`,
    solution: `Leveraged Three.js's GLTFLoader, built a custom lighting rig with environment maps, and implemented smooth orbit controls with momentum. File parsing happens entirely client-side.`,
    image: null,
    gradient: 'from-orange-600/20 to-red-600/20',
    accent: '#ff6b35',
    tags: ['Three.js', 'WebGL', 'React', 'GLTFLoader', 'Orbit Controls'],
    github: 'https://github.com',
    live: 'https://example.com',
    featured: false,
    learnings: 'Gained deep knowledge of WebGL, 3D transformations, lighting models, and browser file APIs.',
  },
  {
    id: 5,
    slug: 'verdant-app',
    title: 'Verdant — Plant Care',
    description: 'A mobile-first app that helps users track plant watering schedules with smart reminders and a care history log.',
    longDescription: `Verdant started as a fun side project when my houseplants kept dying. I wanted a dead-simple app for tracking watering schedules — no bloat, just what you need.\n\nThe app uses local notifications, a clean swipe-based UI, and persists data locally so it works offline.`,
    problem: `Existing plant apps are overcomplicated. I just needed a simple way to log when I last watered each plant and get reminded when it was time again.`,
    solution: `Built with React Native and Expo for cross-platform support, local SQLite for offline-first data, and Expo Notifications for push reminders.`,
    image: null,
    gradient: 'from-green-600/20 to-emerald-600/20',
    accent: '#10b981',
    tags: ['React Native', 'Expo', 'SQLite', 'Push Notifications', 'Offline-first'],
    github: 'https://github.com',
    live: 'https://example.com',
    featured: false,
    learnings: 'First mobile app — learned React Native architecture, Expo ecosystem, and offline-first data patterns.',
  },
  {
    id: 6,
    slug: 'orbit-collab',
    title: 'Orbit — Collaborative Notes',
    description: 'A real-time collaborative note-taking app with live cursors, markdown support, and instant sync across devices.',
    longDescription: `Orbit was built to understand how real-time collaborative editing works under the hood. I implemented a simplified version of Operational Transforms to handle concurrent edits.\n\nThe app supports markdown rendering, live cursors that show collaborator positions, and instant sync via WebSockets.`,
    problem: `I wanted to understand how apps like Notion and Google Docs handle simultaneous edits without conflicts — so I built a simplified version from scratch.`,
    solution: `Used WebSockets via Socket.io for real-time sync, implemented basic OT (Operational Transforms) for conflict resolution, and used a ProseMirror-based editor for rich text.`,
    image: null,
    gradient: 'from-sky-600/20 to-indigo-600/20',
    accent: '#38bdf8',
    tags: ['Next.js', 'Socket.io', 'Operational Transforms', 'ProseMirror', 'Redis'],
    github: 'https://github.com',
    live: 'https://example.com',
    featured: false,
    learnings: 'Learned WebSocket architecture, OT algorithms, and the complexity of distributed state management.',
  },
]

// Experience — set to empty array to hide the section
export const experience = [
  {
    company: 'TechCorp Inc.',
    role: 'Frontend Developer Intern',
    period: 'May 2024 — Aug 2024',
    type: 'Internship',
    description: 'Worked on the consumer-facing dashboard team, shipping 3 new features and fixing 20+ bugs across the React codebase.',
    highlights: [
      'Built a reusable data table component now used across 6 product pages',
      'Reduced initial page load time by 22% through lazy loading and code splitting',
      'Collaborated daily with designers in Figma to implement pixel-perfect UIs',
      'Wrote unit tests with Vitest, increasing coverage from 45% to 72%',
    ],
    logo: 'T',
    color: '#4f8ef7',
  },
]
